app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: ghcr.io/gethomepage/homepage
            tag: v0.8.8
  service:
    main:
      ports:
        http:
          port: 3000
          protocol: HTTP
  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host home.techpolice.online
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: http
      tls:
        - hosts:
            - *host
          secretName: homepage-tls-certificate
  persistence:
    config:
      enabled: true
      type: configMap
      name: homepage-config
      globalMounts:
        - path: /app/config/settings.yaml
          subPath: settings.yaml
        - path: /app/config/widgets.yaml
          subPath: widgets.yaml
        - path: /app/config/services.yaml
          subPath: services.yaml
        - path: /app/config/bookmarks.yaml
          subPath: bookmarks.yaml
  configMaps:
    config:
      enabled: true
      data:
        settings.yaml: |
          background: https://image-0.uhdpaper.com/wallpaper/windows-11-365-background-4k-wallpaper-uhdpaper.com-142@0@h.jpg
          cardBlur: md
          theme: dark
          headerStyle: boxed
          hideVersion: true
        widgets.yaml: |
          - search:
              provider: google
              target: _blank
        services.yaml: |
          - Popular:
            - Matrix:
                href: https://chat.techpolice.online
                description: Chat client
                icon: element.svg
          - Management:
            - Kanidm:
                href: https://auth.techpolice.online
                description: Identity management
                icon: https://auth.techpolice.online/pkg/img/logo-square.svg
          - Development:
            - Gitea:
                href: https://git.techpolice.online
                description: Git forge
                icon: gitea.svg
            - Woodpecker:
                href: https://ci.techpolice.online
                description: Continuous integration
                icon: woodpecker-ci.svg
            - ArgoCD:
                href: https://argocd.techpolice.online
                description: Continuous deployment
                icon: argocd.svg
            - Registry:
                href: https://registry.techpolice.online
                description: Container registry
                icon: docker.svg
            - Grafana:
                href: https://grafana.techpolice.online
                description: Observability dashboards
                icon: grafana.svg
          - Utilities:
            - Excalidraw:
                href: https://draw.techpolice.online
                description: Virtual whiteboard
                icon: excalidraw.svg
            - Speedtest:
                href: https://speedtest.techpolice.online
                description: Internal network speed test
                icon: openspeedtest.png
        bookmarks.yaml: |
          - Homelab:
            - Documentation:
              - href: https://homelab.techpolice.online
                icon: google-docs.svg
            - Public homelab repository:
              - href: https://github.com/anhtung19x9/homelab
                icon: github.svg
          - Managed services:
            - Cloudflare:
              - href: https://dash.cloudflare.com
                icon: cloudflare.svg
          - Infrastructure:
            - pfSense:
              - href: https://10.17.0.1:8443
                icon: router.svg