elementweb:
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      external-dns.alpha.kubernetes.io/target: "homelab-tunnel.vmogroup.online"
      external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
    hosts:
      - host: &frontend_host chat.vmogroup.online
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: element-tls-certificate
        hosts:
          - *frontend_host
  config:
    default:
      base_url: https://matrix.vmogroup.online
      server_name: vmogroup.online

dendrite:
  dendrite_config:
    global:
      server_name: matrix.vmogroup.online
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hostName: matrix.vmogroup.online
    tls:
      - hosts:
          - matrix.vmogroup.online
        secretName: matrix-tls-certificate
  postgresql:
    enabled: true
