elementweb:
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      external-dns.alpha.kubernetes.io/target: "homelab-tunnel.techpolice.online"
      external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
    hosts:
      - host: &frontend_host chat.techpolice.online
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: element-tls-certificate
        hosts:
          - *frontend_host
  config:
    default:
      base_url: https://matrix.techpolice.online
      server_name: techpolice.online

dendrite:
  dendrite_config:
    global:
      server_name: matrix.techpolice.online
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hostName: matrix.techpolice.online
    tls:
      - hosts:
          - matrix.techpolice.online
        secretName: matrix-tls-certificate
  postgresql:
    enabled: true
