ingress-nginx:
  controller:
    admissionWebhooks:
      timeoutSeconds: 30
      annotations:
        argocd.argoproj.io/hook: PostSync
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    service:
      type: ClusterIP
  tcp:
    22: gitea/gitea-ssh:22